spring.application.name=camel-microservice-a

camel.component.kafka.brokers=localhost:9092
camel.component.kafka.key-serializer=org.apache.kafka.common.serialization.StringSerializer
camel.component.kafka.value-serializer=org.apache.kafka.common.serialization.StringSerializer
