version: '3.1'

services:

  db:
    container_name: maria-db
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"