spring.application.name=camel-microservice-b
server.port=8081

camel.component.kafka.brokers=localhost:9092
camel.component.kafka.group-id=kafka-consumer-group
camel.component.kafka.auto-offset-reset=earliest
camel.component.kafka.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
camel.component.kafka.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer